# Generated by Django 4.2.1 on 2023-07-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="userstatus",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
