# Generated by Django 4.2.1 on 2023-08-17 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_medicine"),
    ]

    operations = [
        migrations.CreateModel(
            name="symptoms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("age", models.CharField(max_length=80)),
                ("symptoms", models.CharField(max_length=30)),
                ("sex", models.ImageField(max_length=30, upload_to="")),
                ("symptomstatus", models.CharField(max_length=10)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.patientreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("age", models.CharField(max_length=80)),
                ("prescription", models.ImageField(upload_to="images")),
                ("sex", models.ImageField(max_length=30, upload_to="")),
                ("prescriptionstatus", models.CharField(max_length=10)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.patientreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification", models.CharField(max_length=30)),
                ("date", models.DateField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "pharmacyreg_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.pharmacyreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="complaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("complaints", models.CharField(max_length=500)),
                ("date", models.DateField(max_length=20)),
                ("replay", models.CharField(default="No replay", max_length=500)),
                ("complaintstatus", models.CharField(max_length=20)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.patientreg",
                    ),
                ),
            ],
        ),
    ]
