# Generated by Django 4.2.1 on 2023-08-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_remove_symptoms_sex_symptoms_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="pharmacyreg_id",
            new_name="pharmacy_id",
        ),
    ]
