# Generated by Django 4.2.1 on 2023-09-09 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("mediciename", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="images")),
                ("date", models.DateField(max_length=20)),
                ("price", models.CharField(max_length=30)),
                ("cartstatus", models.CharField(max_length=30)),
                (
                    "medicine_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.medicine"
                    ),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.patientreg",
                    ),
                ),
            ],
        ),
    ]
