# Generated by Django 4.2.1 on 2023-10-03 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_rename_mediciename_cart_medicinename_cart_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="order_price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.CharField(max_length=20)),
                ("price_status", models.CharField(max_length=20)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.patientreg",
                    ),
                ),
            ],
        ),
    ]
